### ISSUE TITLE
[FR] Mailing list

### ISSUE THREAD

**Issue by webknjaz** [GDG-Ukraine/gdg.org.ua#16] opened 2013-10-02 13:53 UTC
Implement/choose/install $sbj.
Probably gmail acc with SMTP would be enough while we don't have huge amount attendees. It has 400 sent mails per day limit. However there are over 4000 in our DB.
That's a topic for discussions.

**Comment by webknjaz** [comment] 2015-12-29 22:49
#26

**Comment by anxolerd** [comment] 2016-01-19 21:43
Closing as duplicate of #26, which has more precise title.

**Closed by anxolerd** 2016-01-19 21:43 UTC
Labels: duplicate, feature
